\hypertarget{classphys_1_1Exception}{
\section{phys::Exception Class Reference}
\label{dc/d47/classphys_1_1Exception}\index{phys::Exception@{phys::Exception}}
}


This is the exception thrown by most physgame system that can throw exceptions.  




{\ttfamily \#include $<$exception.h$>$}

\subsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
\hyperlink{classphys_1_1Exception_a73fd1d2603e30f5663fef2d64df5179f}{Exception} (const \hyperlink{namespacephys_aa03900411993de7fbfec4789bc1d392e}{String} \&Message, bool Logged\_\-=false)
\begin{DoxyCompactList}\small\item\em Simple Constructor. \item\end{DoxyCompactList}\item 
virtual \hyperlink{namespacephys_aa03900411993de7fbfec4789bc1d392e}{String} \hyperlink{classphys_1_1Exception_ac929f9b3929526eec6e6b581c9a9dd73}{what} ()  throw ()
\begin{DoxyCompactList}\small\item\em Retrieves the error message. \item\end{DoxyCompactList}\item 
bool \hyperlink{classphys_1_1Exception_ab1399e25435c390db551855fda338951}{HasBeenLogged} ()
\begin{DoxyCompactList}\small\item\em Has this exception been on a trip through the Logger? \item\end{DoxyCompactList}\end{DoxyCompactItemize}


\subsection{Detailed Description}
This is the exception thrown by most physgame system that can throw exceptions. In general they work like std::exception, but also track whether they have been logged yet. 

Definition at line 57 of file exception.h.



\subsection{Constructor \& Destructor Documentation}
\hypertarget{classphys_1_1Exception_a73fd1d2603e30f5663fef2d64df5179f}{
\index{phys::Exception@{phys::Exception}!Exception@{Exception}}
\index{Exception@{Exception}!phys::Exception@{phys::Exception}}
\subsubsection[{Exception}]{\setlength{\rightskip}{0pt plus 5cm}phys::Exception::Exception (const {\bf String} \& {\em Message}, \/  bool {\em Logged\_\-} = {\ttfamily false})}}
\label{dc/d47/classphys_1_1Exception_a73fd1d2603e30f5663fef2d64df5179f}


Simple Constructor. 


\begin{DoxyParams}{Parameters}
\item[{\em Message}]The Error you want stored in the exception. \item[{\em Logged\_\-}]Has this exception already been sent to tthe logger \end{DoxyParams}


Definition at line 46 of file exception.cpp.



\subsection{Member Function Documentation}
\hypertarget{classphys_1_1Exception_ab1399e25435c390db551855fda338951}{
\index{phys::Exception@{phys::Exception}!HasBeenLogged@{HasBeenLogged}}
\index{HasBeenLogged@{HasBeenLogged}!phys::Exception@{phys::Exception}}
\subsubsection[{HasBeenLogged}]{\setlength{\rightskip}{0pt plus 5cm}bool phys::Exception::HasBeenLogged ()}}
\label{dc/d47/classphys_1_1Exception_ab1399e25435c390db551855fda338951}


Has this exception been on a trip through the Logger? 

\begin{DoxyReturn}{Returns}
A bool storing true if it has and false if it has not. 
\end{DoxyReturn}


Definition at line 51 of file exception.cpp.

\hypertarget{classphys_1_1Exception_ac929f9b3929526eec6e6b581c9a9dd73}{
\index{phys::Exception@{phys::Exception}!what@{what}}
\index{what@{what}!phys::Exception@{phys::Exception}}
\subsubsection[{what}]{\setlength{\rightskip}{0pt plus 5cm}{\bf String} phys::Exception::what ()  throw ()\hspace{0.3cm}{\ttfamily  \mbox{[}virtual\mbox{]}}}}
\label{dc/d47/classphys_1_1Exception_ac929f9b3929526eec6e6b581c9a9dd73}


Retrieves the error message. 

\begin{DoxyReturn}{Returns}
This returns a string that is the stored error message. 
\end{DoxyReturn}


Definition at line 56 of file exception.cpp.



The documentation for this class was generated from the following files:\begin{DoxyCompactItemize}
\item 
exception.h\item 
exception.cpp\end{DoxyCompactItemize}
