<map id="Mezzanine::NetworkURLException" name="Mezzanine::NetworkURLException">
<area shape="rect" id="node2" href="$classMezzanine_1_1NetworkException.html" title="Thrown when something unknown causes network IO to fail. " alt="" coords="19,237,219,267"/>
<area shape="rect" id="node4" href="$classMezzanine_1_1IOException.html" title="Thrown when there was an issue with IO but very little was known about it. " alt="" coords="36,160,201,189"/>
<area shape="rect" id="node6" href="$classMezzanine_1_1Exception.html" title="This is the exception thrown by most Mezzanine system that can throw exceptions. " alt="" coords="44,83,193,112"/>
<area shape="rect" id="node8" title="STL class. " alt="" coords="67,5,171,35"/>
</map>
