<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<title>PhysGameEngine: phys::Exception Class Reference</title>
<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<link href="../../doxygen.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<!-- Generated by Doxygen 1.7.1 -->
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="../../index.html"><span>Main&nbsp;Page</span></a></li>
      <li><a href="../../pages.html"><span>Related&nbsp;Pages</span></a></li>
      <li><a href="../../namespaces.html"><span>Namespaces</span></a></li>
      <li class="current"><a href="../../annotated.html"><span>Classes</span></a></li>
      <li><a href="../../files.html"><span>Files</span></a></li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="../../annotated.html"><span>Class&nbsp;List</span></a></li>
      <li><a href="../../hierarchy.html"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="../../functions.html"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
  <div class="navpath">
    <ul>
      <li><a class="el" href="../../df/dec/namespacephys.html">phys</a>      </li>
      <li><a class="el" href="../../dc/d47/classphys_1_1Exception.html">phys::Exception</a>      </li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a>  </div>
  <div class="headertitle">
<h1>phys::Exception Class Reference</h1>  </div>
</div>
<div class="contents">
<!-- doxytag: class="phys::Exception" -->
<p>This is the exception thrown by most physgame system that can throw exceptions.  
<a href="#_details">More...</a></p>

<p><code>#include &lt;<a class="el" href="../../dd/d2d/exception_8h_source.html">exception.h</a>&gt;</code></p>

<p><a href="../../d5/dfb/classphys_1_1Exception-members.html">List of all members.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d47/classphys_1_1Exception.html#a73fd1d2603e30f5663fef2d64df5179f">Exception</a> (const <a class="el" href="../../df/dec/namespacephys.html#aa03900411993de7fbfec4789bc1d392e">String</a> &amp;Message, bool Logged_=false)</td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Simple Constructor.  <a href="#a73fd1d2603e30f5663fef2d64df5179f"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">virtual <a class="el" href="../../df/dec/namespacephys.html#aa03900411993de7fbfec4789bc1d392e">String</a>&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d47/classphys_1_1Exception.html#ac929f9b3929526eec6e6b581c9a9dd73">what</a> ()  throw ()</td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Retrieves the error message.  <a href="#ac929f9b3929526eec6e6b581c9a9dd73"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">bool&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../dc/d47/classphys_1_1Exception.html#ab1399e25435c390db551855fda338951">HasBeenLogged</a> ()</td></tr>
<tr><td class="mdescLeft">&nbsp;</td><td class="mdescRight">Has this exception been on a trip through the Logger?  <a href="#ab1399e25435c390db551855fda338951"></a><br/></td></tr>
</table>
<hr/><a name="_details"></a><h2>Detailed Description</h2>
<p>This is the exception thrown by most physgame system that can throw exceptions. </p>
<p>In general they work like std::exception, but also track whether they have been logged yet. </p>

<p>Definition at line <a class="el" href="../../dd/d2d/exception_8h_source.html#l00057">57</a> of file <a class="el" href="../../dd/d2d/exception_8h_source.html">exception.h</a>.</p>
<hr/><h2>Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a73fd1d2603e30f5663fef2d64df5179f"></a><!-- doxytag: member="phys::Exception::Exception" ref="a73fd1d2603e30f5663fef2d64df5179f" args="(const String &amp;Message, bool Logged_=false)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">phys::Exception::Exception </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="../../df/dec/namespacephys.html#aa03900411993de7fbfec4789bc1d392e">String</a> &amp;&nbsp;</td>
          <td class="paramname"> <em>Message</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">bool&nbsp;</td>
          <td class="paramname"> <em>Logged_</em> = <code>false</code></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td><td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Simple Constructor. </p>
<dl><dt><b>Parameters:</b></dt><dd>
  <table border="0" cellspacing="2" cellpadding="0">
    <tr><td valign="top"></td><td valign="top"><em>Message</em>&nbsp;</td><td>The Error you want stored in the exception. </td></tr>
    <tr><td valign="top"></td><td valign="top"><em>Logged_</em>&nbsp;</td><td>Has this exception already been sent to tthe logger </td></tr>
  </table>
  </dd>
</dl>

<p>Definition at line <a class="el" href="../../de/d9e/exception_8cpp_source.html#l00046">46</a> of file <a class="el" href="../../de/d9e/exception_8cpp_source.html">exception.cpp</a>.</p>

</div>
</div>
<hr/><h2>Member Function Documentation</h2>
<a class="anchor" id="ab1399e25435c390db551855fda338951"></a><!-- doxytag: member="phys::Exception::HasBeenLogged" ref="ab1399e25435c390db551855fda338951" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">bool phys::Exception::HasBeenLogged </td>
          <td>(</td>
          <td class="paramname"></td>
          <td>&nbsp;)&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Has this exception been on a trip through the Logger? </p>
<dl class="return"><dt><b>Returns:</b></dt><dd>A bool storing true if it has and false if it has not. </dd></dl>

<p>Definition at line <a class="el" href="../../de/d9e/exception_8cpp_source.html#l00051">51</a> of file <a class="el" href="../../de/d9e/exception_8cpp_source.html">exception.cpp</a>.</p>

</div>
</div>
<a class="anchor" id="ac929f9b3929526eec6e6b581c9a9dd73"></a><!-- doxytag: member="phys::Exception::what" ref="ac929f9b3929526eec6e6b581c9a9dd73" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="../../df/dec/namespacephys.html#aa03900411993de7fbfec4789bc1d392e">String</a> phys::Exception::what </td>
          <td>(</td>
          <td class="paramname"></td>
          <td>&nbsp;)&nbsp;</td>
          <td>  throw ()<code> [virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Retrieves the error message. </p>
<dl class="return"><dt><b>Returns:</b></dt><dd>This returns a string that is the stored error message. </dd></dl>

<p>Definition at line <a class="el" href="../../de/d9e/exception_8cpp_source.html#l00056">56</a> of file <a class="el" href="../../de/d9e/exception_8cpp_source.html">exception.cpp</a>.</p>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li><a class="el" href="../../dd/d2d/exception_8h_source.html">exception.h</a></li>
<li><a class="el" href="../../de/d9e/exception_8cpp_source.html">exception.cpp</a></li>
</ul>
</div>
<hr class="footer"/><address class="footer"><small>Generated on Wed Jan 19 2011 13:20:24 for PhysGameEngine by&nbsp;
<a href="http://www.doxygen.org/index.html">
<img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.7.1 </small></address>
</body>
</html>
